Repository ManageIQ/manageiq-appliance, pull requests merged in 2018-10, with the labels that each got.

#209 Add max-time to curl commands
  LINK/usr/bin/cloud_ds_check.sh
Labels: bug

#206 Move from apache module mod_auth_kerb to mod_auth_gssapi
  TEMPLATE/etc/httpd/conf.d/manageiq-external-auth.conf.erb
Labels: enhancement

#211 [HAMMER] [Changelog] Add updates for beta1.1
  CHANGELOG.md
Labels: documentation

#210 [Changelog] Update for Sprint 96
  CHANGELOG.md
Labels: documentation

#214 Change log time zone and format to match that of the core VMDBLogger
  lib/evm_watchdog.rb
Labels: technical debt
