Repository ManageIQ/manageiq-appliance, pull requests merged in 2018-07, with the labels that each got.

#196 Add .ansible.cfg for ansible-playbook
  LINK/root/.ansible.cfg
Labels: enhancement

#199 Add the [default] header to .ansible.cfg
  LINK/root/.ansible.cfg
Labels: blocker, bug, gaprindashvili/no

#200 Add support for OpenID-Connect
  TEMPLATE/etc/httpd/conf.d/manageiq-external-auth-openidc.conf
  TEMPLATE/etc/httpd/conf.d/manageiq-remote-user-openidc.conf
Labels: enhancement

#195 [Changelog] Add Gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation
