Repository ManageIQ/manageiq-appliance, pull requests merged in 2018-05, with the labels that each got.

#190 Update the included console version to 2.0.2
  manageiq-appliance-dependencies.rb
Labels: blocker, bug, gaprindashvili/yes

#191 Add cache headers for webpack
  COPY/etc/httpd/conf.d/manageiq-https-application.conf
Labels: bug, performance

#192 Update the console to version 2.0.3
  manageiq-appliance-dependencies.rb
Labels: blocker, bug, gaprindashvili/yes

#193 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#194 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: test
