Repository ManageIQ/manageiq-appliance, pull requests merged in 2018-04, with the labels that each got.

#185 httpd reload is not needed with copytruncate
  COPY/etc/logrotate.d/miq_logs.conf
Labels: bug, fine/yes, gaprindashvili/yes

#186 Bump to ruby 2.3.6
  .travis.yml
Labels: test

#184 [Changelog] Update for Sprint 81
  CHANGELOG.md
Labels: documentation

#188 Bump appliance_console for db_maintenance fix
  manageiq-appliance-dependencies.rb
Labels: bug, gaprindashvili/yes

#189 mod_ssl rpm loads the module so we don't have to
  COPY/etc/httpd/conf.d/manageiq-https.conf
Labels: bug, gaprindashvili/yes
