Repository ManageIQ/manageiq-appliance, pull requests merged in 2018-02, with the labels that each got.

#179 [Changelog] Update for Sprint 78 and Gaprindashvili-1 release
  CHANGELOG.md
Labels: documentation

#180 Remove reindex and vacuum scripts
  LINK/usr/bin/hourly_reindex_metrics_tables
  LINK/usr/bin/hourly_reindex_miq_queue_table
  LINK/usr/bin/hourly_reindex_miq_workers_table
  LINK/usr/bin/periodic_vacuum_full_tables
Labels: enhancement, gaprindashvili/yes

#181 Optimize PostgreSQL Settings for 4x12GB Applaince
  COPY/etc/manageiq/postgresql.conf.d/01_miq_overrides.conf
Labels: enhancement
