Repository ManageIQ/manageiq-appliance, pull requests merged in 2019-03, with the labels that each got.

#228 Update to PG 10
  COPY/etc/logrotate.d/miq_logs.conf
  COPY/etc/manageiq/postgresql.conf.d/01_miq_overrides.conf
  COPY/etc/systemd/system/rh-postgresql95-repmgr.service.d/config_file.conf
  LINK/etc/default/evm_postgres
  LINK/etc/sudoers.d/repmgr
  LINK/usr/bin/miq_postgres_upgrade.sh
  TEMPLATE/var/lib/pgsql/data/pg_hba.conf
  TEMPLATE/var/lib/pgsql/data/pg_ident.conf
  TEMPLATE/var/lib/pgsql/data/postgresql.conf
Labels: enhancement, hammer/no

#229 Update to manageiq-appliance_console 4.0
  manageiq-appliance-dependencies.rb
Labels: enhancement

#230 Fix shebang for evm_watchdog
  LINK/usr/bin/evm_watchdog.rb
Labels: hammer/no

#231 [Changelog] Update for Sprint 107
  CHANGELOG.md
Labels: documentation
