Repository ManageIQ/manageiq-appliance, pull requests merged in 2019-07, with the labels that each got.

#244 Update dependency on manageiq-appliance_console
  manageiq-appliance-dependencies.rb
Labels: bug

#247 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#248 Do not forward /ui/service/console to the sui index.html
  COPY/etc/httpd/conf.d/manageiq-redirects-ui
Labels: bug, hammer/no, ivanchuk/yes

#246 Remove httpd config for embedded ansible
  COPY/etc/httpd/conf.d/manageiq-https-application.conf
  COPY/etc/httpd/conf.d/manageiq-redirects-ansible
  COPY/etc/httpd/conf.d/manageiq-redirects-ui
Labels: embedded ansible, ivanchuk/yes, technical debt
