Repository ManageIQ/manageiq-appliance, pull requests merged in 2019-05, with the labels that each got.

#235 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: changelog/no, test

#236 Alter postgres conf for built in logical replication
  COPY/etc/manageiq/postgresql.conf.d/01_miq_overrides.conf
Labels: changelog/yes, enhancement, hammer/no

#234 Add sssd.conf.erb to TEMPLATE directory for authselect support
  TEMPLATE/etc/sssd/sssd.conf.erb
Labels: bug, enhancement, hammer/no

#237 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#238 [Changelog] Update for Sprint 112
  CHANGELOG.md
Labels: documentation
