Repository ManageIQ/manageiq-appliance, pull requests merged in 2019-01, with the labels that each got.

#219 Detach actioncable from the WebsocketServer and run it with the UI
  COPY/etc/httpd/conf.d/manageiq-balancer-ui.conf
  COPY/etc/httpd/conf.d/manageiq-redirects-ui
  COPY/etc/httpd/conf.d/manageiq-redirects-websocket
Labels: enhancement

#222 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#223 [Changelog] Update for Sprint 102
  CHANGELOG.md
Labels: documentation

#224 Let API requests go through apache if they contain a CSRF token
  TEMPLATE/etc/httpd/conf.d/manageiq-external-auth.conf.erb
Labels: hammer/no
