Repository ManageIQ/manageiq-appliance, pull requests merged in 2019-08, with the labels that each got.

#249 Correct the ansible config section name
  LINK/root/.ansible.cfg
Labels: bug, embedded ansible, ivanchuk/yes

#250 [Changelog] Update for Sprint 117
  CHANGELOG.md
Labels: documentation

#251 [Changelog] Update for Ivanchuk Beta2
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#252 Add default roles paths to .ansible.cfg
  LINK/root/.ansible.cfg
Labels: bug, embedded ansible, ivanchuk/yes

#253 Use console version 5.0.2
  manageiq-appliance-dependencies.rb
Labels: blocker, bug, ivanchuk/yes
