Repository ManageIQ/manageiq-appliance, pull requests merged in 2020-04, with the labels that each got.

#278 Update dependency on manageiq-appliance_console
  manageiq-appliance-dependencies.rb
Labels: bug, ivanchuk/backported, jansa/backported

#279 Bump manageiq-appliance_console to v5.4.0
  manageiq-appliance-dependencies.rb
Labels: enhancement, jansa/yes?

#280 Remove .bowerrc
  LINK/root/.bowerrc
Labels: cleanup
