Repository ManageIQ/manageiq-appliance, pull requests merged in 2020-10, with the labels that each got.

#297 remove sudo false from travis yaml
  .travis.yml
Labels: cleanup

#298 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: dependencies

#286 Switch to manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  Gemfile
Labels: developer
