Repository ManageIQ/manageiq-appliance, pull requests merged in 2020-05, with the labels that each got.

#284 OIDC - bump dependency of appliance_console to 5.5
  manageiq-appliance-dependencies.rb
Labels: dependencies, enhancement, jansa/yes?

#285 Add Travis badge
  README.md
Labels: developer

#277 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
