Repository ManageIQ/manageiq-appliance, pull requests merged in 2021-09, with the labels that each got.

#329 use shell primitives for /etc/default/evm
  LINK/etc/default/evm
Labels: bug, performance

#328 Run ruby evm_server.rb directly
  COPY/usr/lib/systemd/system/evmserverd.service
  LINK/usr/bin/evminit.sh
  LINK/usr/bin/evmserver.sh
Labels: refactoring

#327 Replace evm-watchdog with manageiq-db-ready
  COPY/usr/lib/systemd/system/evm-watchdog.service
  COPY/usr/lib/systemd/system/evmserverd.service
  COPY/usr/lib/systemd/system/manageiq-db-ready.service
  LINK/usr/bin/evm_watchdog
  LINK/usr/bin/evm_watchdog.rb
  LINK/usr/bin/manageiq-db-ready
  lib/evm_watchdog.rb
  spec/evm_watchdog_spec.rb
Labels: enhancement

#331 Add execute bit to manageiq-db-ready
  COPY/usr/lib/systemd/system/manageiq-db-ready.service
  LINK/usr/bin/manageiq-db-ready
Labels: bug

#334 Fix execjs runtime error
  LINK/etc/default/manageiq.properties
Labels: bug
