Repository ManageIQ/manageiq-appliance, pull requests merged in 2022-02, with the labels that each got.

#346 Revert "Tell postgres client to use OS cert bundle for ssl root keys"
  COPY/etc/default/manageiq.properties
Labels: bug

#347 Remove specs and Ruby
  .codeclimate.yml
  .gitignore
  .rspec
  .rubocop.yml
  .rubocop_cc.yml
  .rubocop_local.yml
  .travis.yml
  .yamllint
  Gemfile
  README.md
  Rakefile
  spec/spec_helper.rb
Labels: technical debt

#352 Rename the evminit.service description
  COPY/usr/lib/systemd/system/evminit.service
Labels: cleanup

#350 Fix initial permissions of log files
  COPY/usr/bin/evminit.sh
Labels: bug, wip

#348 Prevent logrotate from creating 0644 log files
  COPY/etc/logrotate.d/miq_logs.conf
Labels: bug, wip

#345 fix quoted strings in properties files
  COPY/etc/default/evm
Labels: bug
