Repository ManageIQ/manageiq-appliance, pull requests merged in 2024-05, with the labels that each got.

#384 Rework Kafka health check in manageiq-messaging-ready
  COPY/usr/bin/manageiq-messaging-ready
Labels: bug

#385 Set the OPENTOFU_RUNNER_URL ENV var
  COPY/etc/default/manageiq.properties
Labels: enhancement, radjabov/yes

#386 Move TERRAFORM_RUNNER_URL to appliance specific properties
  COPY/etc/default/manageiq-appliance.properties
  COPY/etc/default/manageiq.properties
Labels: bug, radjabov/yes?
